// Config loader - handles optional user config.ts (generated by dotter)
// If config.ts doesn't exist, uses defaults. If it exists, merges it.

import defaults from "./config.defaults"
import type { Config } from "./config.defaults"

// Mutable config that starts as defaults, can be updated by loading user config
let _config: Config = { ...defaults }

// Synchronous getter - always returns valid config
export function getConfig(): Config {
  return _config
}

// Load user config.ts if it exists, merge with defaults
export async function loadUserConfig(): Promise<void> {
  try {
    // Dynamic import - will throw if file doesn't exist
    const userConfig = await import("./config")
    _config = { ...defaults, ...userConfig.default }
    console.log("[config] loaded user config")
  } catch {
    console.log("[config] using defaults (no config.ts found)")
  }
}

// Re-export types and defaults for convenience
export { defaults }
export type { Config }
